version: "3.9"

services:
  backend:
    build:
      context: .
      target: development
    container_name: spring-backend
    ports:
      - "8080:8080"
    volumes:
      - .:/app
      - m2_cache:/root/.m2
    env_file: .env.backend
    depends_on:
      db:
        condition: service_healthy
    networks:
      - default
      - smart-parking-dev-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/actuator/health"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 20s

  db:
    image: postgres:16-alpine
    container_name: postgres-db
    restart: always
    env_file:
      - .env.database
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d smart_parking"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s

volumes:
  pgdata:
  m2_cache:

networks:
  smart-parking-dev-network:
    external: true