spring.application.name=Smart-Parking-System

spring.datasource.url=jdbc:postgresql://ep-jolly-meadow-ad4p6epl-pooler.c-2.us-east-1.aws.neon.tech/smart-parking?sslmode=require
spring.datasource.username=neondb_owner
spring.datasource.password=npg_qi9zKtn1aRxy

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.open-in-view=false