spring:
  application:
    name: SmartParking

  # Database configuration
  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}

  # Hibernate configuration
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect

# Khalti payment integration
khalti:
  initiate:
    url: https://dev.khalti.com/api/v2/epayment/initiate/
  verify:
    url: https://dev.khalti.com/api/v2/epayment/lookup/
  secret:
    key: "Key 05bf95cc57244045b8df5fad06748dab"

# Actuator Management Endpoints
management:
  endpoints:
    web:
      base-path: /api
      exposure:
        include: health
  endpoint:
    health:
      show-details: always